//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfortel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Id { get; set; }
        public System.DateTime DatePayment { get; set; }
        public int PaymentType { get; set; }
        public float Amount { get; set; }
        public int ReservationId { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
